jetcache:
  statIntervalMinutes: 15
  areaInCacheName: false
  hiddenPackages: com.ljt.study.tools
  local:
    default:
      type: caffeine
      keyConvertor: fastjson
      expireAfterWriteInMillis: 5000
#      expireAfterAccessInMillis: 5000
  remote:
    default:
      type: redis
      keyConvertor: fastjson
#      valueEncoder: java
#      valueDecoder: java
      expireAfterWriteInMillis: 5000
      poolConfig:
        minIdle: 5
        maxIdle: 20
        maxTotal: 50
      host: 127.0.0.1
      port: 6379