package com.ljt.study.tools.http;

import okhttp3.*;

import java.io.IOException;

/**
 * @author LiJingTang
 * @date 2021-09-24 17:45
 */
class OkHttpTest {

    static final String CHECK_VALUE = "TUlJRzh3WUpLb1pJaHZjTkFRY0NvSUlHNURDQ0J1QUNBUUV4RHpBTkJnbGdoa2dCWlFNRUFnRUZBREJpQmdrcWhraUc5dzBCQndHZ1ZRUlRleUp0WlhKZlkzVnpkRjlwWkNJNklqWTJOall3TURBeE1EYzBNakl4TXpVaUxDSjFjMlZ5WDJOMWMzUmZhV1FpT2lJMk5qWTJNREF3TVRBNU9EVTNNek16SWl3aWRtVnljMmx2YmlJNklqRXdJbjJnZ2dUVU1JSUUwRENDQTdpZ0F3SUJBZ0lGUkJLUk9VY3dEUVlKS29aSWh2Y05BUUVMQlFBd1dERUxNQWtHQTFVRUJoTUNRMDR4TURBdUJnTlZCQW9NSjBOb2FXNWhJRVpwYm1GdVkybGhiQ0JEWlhKMGFXWnBZMkYwYVc5dUlFRjFkR2h2Y21sMGVURVhNQlVHQTFVRUF3d09RMFpEUVNCQlExTWdUME5CTXpFd0hoY05NakV3TmpFeE1EWTFOREk0V2hjTk1qWXdOakV4TURZMU5ESTRXakIvTVFzd0NRWURWUVFHRXdKRFRqRVhNQlVHQTFVRUNnd09RMFpEUVNCQlExTWdUME5CTXpFeEVUQVBCZ05WQkFzTUNFeHZZMkZzSUZKQk1Sa3dGd1lEVlFRTERCQlBjbWRoYm1sNllYUnBiMjVoYkMweE1Ta3dKd1lEVlFRRERDQXdOVEZBU0VZd01qWTJRRTQ1TVRNMk1ERXlNVTFCTTBGQ1VUVXlNRXRBTWpDQ0FTSXdEUVlKS29aSWh2Y05BUUVCQlFBRGdnRVBBRENDQVFvQ2dnRUJBS3hhZmgyVktGZTNFMzN6R0pUcmJxOTRZR0dMS1lIS0EvYk5iMWxZQ3dqTGI0eGxHZ1FtV2ZkaU5yakxwRkNPRER4NDFCUngzcmoxd1RkekpIWDJVZ0ptYWlEU2F5VnhRQm5PeE5uOXZKUHY2V1M1ZEVpb0FKUTFmREF6dmhUbmpQcVprZUhsSitnU0pQc3NlZklvTVliMEplNmNEa1IvQTYzSkJGaW1kaXBLbHQxZXY1bmJXeHpKNVE2enAzYWx6NVhveTRJaHNZT0Z3TnJlME1NN2xKYWJUaS8vWTlEU25DbHIxL2RTcGFEdEpJOERJM0hWdUNvUGludmJXL29UYTB3VFBRcXZXbFMrR0VhcHl6OFltZ0xsQm5CTW9DN245RzZ1RUI1YU1OZ1FDVDJVUkR6WFN5T1RwNGxMb2JCMm4xV1FHNlJGbnhFSGlEaTBqYjJHNUlFQ0F3RUFBYU9DQVhnd2dnRjBNR3dHQ0NzR0FRVUZCd0VCQkdBd1hqQW9CZ2dyQmdFRkJRY3dBWVljYUhSMGNEb3ZMMjlqYzNBdVkyWmpZUzVqYjIwdVkyNHZiMk56Y0RBeUJnZ3JCZ0VGQlFjd0FvWW1hSFIwY0RvdkwyTnliQzVqWm1OaExtTnZiUzVqYmk5dlkyRXpNUzl2WTJFek1TNWpaWEl3SHdZRFZSMGpCQmd3Rm9BVTRyUUp5ODFob1hOS2VYL3hpb01MM2JSK2pCMHdEQVlEVlIwVEFRSC9CQUl3QURCSUJnTlZIU0FFUVRBL01EMEdDR0NCSElidktnRUVNREV3THdZSUt3WUJCUVVIQWdFV0kyaDBkSEE2THk5M2QzY3VZMlpqWVM1amIyMHVZMjR2ZFhNdmRYTXRNVFF1YUhSdE1EMEdBMVVkSHdRMk1EUXdNcUF3b0M2R0xHaDBkSEE2THk5amNtd3VZMlpqWVM1amIyMHVZMjR2YjJOaE16RXZVbE5CTDJOeWJETXdPRGd1WTNKc01BNEdBMVVkRHdFQi93UUVBd0lHd0RBZEJnTlZIUTRFRmdRVTduSlVLV1h1VDFEb1QxQ0liY1hHTmRtYjVlRXdIUVlEVlIwbEJCWXdGQVlJS3dZQkJRVUhBd0lHQ0NzR0FRVUZCd01FTUEwR0NTcUdTSWIzRFFFQkN3VUFBNElCQVFDL2c2NU5jNVAvK2ppVmJXVDlVZC8zQnkzdjhFREhxR0dBRFQ5ck90VEFTVFBaTE8vNXNvYmZwazV0bG9FKzNtYXZQeWEvYlJVWGJYVmc3b1dkM1ZtRk1objJkTms0Sk9XNkxsMFlpMHNGREJtMVlRSE1CaENWclo3QSt2U3dsWS9tWk1mMUFDcUwrZjgvNElJN3I4eXF6dmtYZlkzN0xWeU5Ha3paRDZKdDNkM1FrcmZ4MDFSeDdnR201Vys0QVR6OUE1QUVGNUNNRjBoQ1lWZ0lXQmlaQnBiS1lRUHpZak01TytrcEdRc1BjcGZYclptS3RVWWRSckdBdGZxWjZoK1EyNUVMeUU4cERsS0MvbzZQczFwbGxoemZFUlRjQmU0dGlwSWRESldnM2l0cVhJM3YybkRLMS9CcTVzeHVaRG1yUWw4bkorZ2pkaWhlWE95Z3JhN1pNWUlCakRDQ0FZZ0NBUUV3WVRCWU1Rc3dDUVlEVlFRR0V3SkRUakV3TUM0R0ExVUVDZ3duUTJocGJtRWdSbWx1WVc1amFXRnNJRU5sY25ScFptbGpZWFJwYjI0Z1FYVjBhRzl5YVhSNU1SY3dGUVlEVlFRRERBNURSa05CSUVGRFV5QlBRMEV6TVFJRlJCS1JPVWN3RFFZSllJWklBV1VEQkFJQkJRQXdEUVlKS29aSWh2Y05BUUVCQlFBRWdnRUFWVWloZnBTT2IwYUJHSlpVdHY2NVNLZms2NjVGVWp1blVBcmd2aXVhZHE0RHhtbGN3bW9NcjZWUFZBUE90MDdYWDdIb1Y1QmovRTJRYVVSOG9rM2xMY2JBZjVSNnJmeW5DQXUvWDN4V1JnNDZpMjBCS2VpUlRWVzFDc0FxVlVWQ00vaHJRd0NRbzR5OVpDVDBjdVptREJnMjhPa0NLSmptVmtwVTVrd244dWNIZjVlSTlySWxjcjliVU5PS0lVVWY0NG9uci96RUp4V1JTWExzTzVhd01mU2oyNGFucHhkNCs4OXZaeXg5Q1RrcVdGTVZwb2FsaGtBTTQzY3lqTG1yZnhiTHEvQXYwMDY1SEJidTUzZ1FBUFd4aVZxcDEvSDRVRFBSU045NFRGV1pteDhPWXNyK2NDRUVRLzRlNmFXRHdpa29wVzZHc3hRdVdPNjRCSEVFSHc9PQ==";
    static final String URL = "https://hfpay.cloudpnr.com/api/hfpay/alse/qry004";

    public static void main(String[] args) throws IOException {
        long start = System.currentTimeMillis();

        for (int i = 0; i < 50; i++) {
            RequestBody reqBody = new FormBody.Builder()
                    .add("mer_cust_id", "6666000107422135")
                    .add("version", "10")
                    .add("check_value", CHECK_VALUE)
                    .build();
            Request request = new Request.Builder()
                    .url(URL)
                    .post(reqBody)
                    .build();

            OkHttpClient httpClient = new OkHttpClient();
            Call call = httpClient.newCall(request);
            Response response = call.execute();

            System.out.println(i + "-" + response.code());
        }
        System.out.println(System.currentTimeMillis() - start);
    }

}
