# 供ZK集群自己使用
apiVersion: v1
kind: Service
metadata:
  name: zk-hs
  labels:
    app: zk
spec:
  clusterIP: None
  ports:
  - name: server
    port: 2888
  - name: leader-election
    port: 3888
  selector:
    app: zk
---
# 配置SVC ZK，供canal订阅服务客户端使用
apiVersion: v1
kind: Service
metadata:
  name: zk-cs
  labels:
    app: zk
spec:
  type: NodePort
  ports:
  - name: client
    port: 2181
    # 暴露NODE的端口，不能和已有node port 重复
    nodePort: 32181
    targetPort: 2181
  selector:
    app: zk
---
apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: zk-pdb
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: zk
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: zk
spec:
  selector:
    matchLabels:
      app: zk
  serviceName: zk-hs
  replicas: 1
  updateStrategy:
    type: RollingUpdate
  podManagementPolicy: OrderedReady
  template:
    metadata:
      labels:
        app: zk
    spec:
      restartPolicy: Always
      # 安全认证
      imagePullSecrets:
        - name: qcloudregistrykey
      nodeSelector:
        node: node1
      # 卷定义，数据存储
      volumes:
      - name: apply
        hostPath:
          path: /apply/zk
      containers:
      - name: kubernetes-zookeeper
        imagePullPolicy: Always
        # 镜像地址
        image: "ccr.ccs.tencentyun.com/gwy-base-image/kubernetes-zookeeper:3.4.10"
        resources:
          requests:
            memory: "1Gi"
            cpu: "0.5"
          limits:
            memory: "2Gi"
            cpu: "1"
        ports:
          # 客户端使用的端口
          - name: client
            containerPort: 2181
          # 节点之间通信端口
          - name: server
            containerPort: 2888
          # 选主使用的端口
          - name: leader-election
            containerPort: 3888
        command:
          - sh
          - -c
          - "start-zookeeper \
            --servers=1 \
            --data_dir=/apply/zk/data \
            --data_log_dir=/apply/zk/log \
            --conf_dir=/opt/zookeeper/conf \
            --client_port=2181 \
            --election_port=3888 \
            --server_port=2888 \
            --tick_time=2000 \
            --init_limit=10 \
            --sync_limit=5 \
            --heap=1024M \
            --max_client_cnxns=60 \
            --snap_retain_count=3 \
            --purge_interval=12 \
            --max_session_timeout=40000 \
            --min_session_timeout=4000 \
            --log_level=INFO"
        readinessProbe:
          exec:
            command:
              - sh
              - -c
              - "zookeeper-ready 2181"
          initialDelaySeconds: 10
          timeoutSeconds: 5
        livenessProbe:
          exec:
            command:
              - sh
              - -c
              - "zookeeper-ready 2181"
          initialDelaySeconds: 10
          timeoutSeconds: 5
        # 卷使用
        volumeMounts:
        - name: apply
          mountPath: /apply/zk