apiVersion: v1
kind: Service
metadata:
  name: canal-server-headless
  labels:
    app: canal-server-headless
spec:
  clusterIP: None
  ports:
  - name: admin-port
    port: 11110
  - name: server-port
    port: 11111
  - name: metrics-port
    port: 11112
  - name: exporter-port
    port: 9100
  selector:
    app: canal-server
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: canal-server
spec:
  replicas: 1
  serviceName: "canal-server-headless"
  podManagementPolicy: OrderedReady
  selector:
    matchLabels:
      app: canal-server
  template:
    metadata:
      labels:
        app: canal-server
    spec:
      restartPolicy: Always
      imagePullSecrets:
      - name: qcloudregistrykey
      containers:
      - name: canal-server
        imagePullPolicy: Always
        image: "ccr.ccs.tencentyun.com/gwy-middleware/canal-server:1.1.4"
        resources:
          requests:
            memory: "1Gi"
            cpu: "0.5"
          limits:
            memory: "2Gi"
            cpu: "1"
        env:
        - name: GWY_ENV
          value: "test"
        - name: GWY_SPRING_APPLICATION_NAME
          value: "canal-server"
        - name: canal.register.ip
          value: "canal-server-0.canal-server-headless.default.svc.cluster.local"
        - name: canal.admin.manager
          value: "canal-admin.default.svc.cluster.local:8089"
        - name: canal.admin.port
          value: "11110"
        - name: canal.admin.user
          value: "admin"
        - name: canal.admin.passwd
          value: "4ACFE3202A5FF5CF467898FC58AAB1D615029441"
        # 配置这个环境变量会自动加入集群,不配置这个环境变量为单机模式
        - name: canal.admin.register.cluster
          value: "zk-k8s" # 集群名称
        ports:
        - name: admin-port
          containerPort: 11110
        - name: server-port
          containerPort: 11111
        - name: metrics-port
          containerPort: 11112
        - name: exporter-port
          containerPort: 9100
        # 就绪探针
        readinessProbe:
          tcpSocket:
            port: 11111
          #容器启动后第一次执行探测是需要等待多少秒
          initialDelaySeconds: 30
          #执行探测的频率,默认是10秒
          periodSeconds: 10
          #探测超时时间,默认1秒
          timeoutSeconds: 5
          #探测失败后,最少连续探测成功多少次才被认定为成功,默认是1
          successThreshold: 1
          #探测成功后,最少连续探测失败多少次才被认定为失败,默认是3
          failureThreshold: 3
        # 存活探针
        livenessProbe:
          tcpSocket:
            port: 11111
          initialDelaySeconds: 60
          periodSeconds: 10
          timeoutSeconds: 5
