spring:
  main:
    web-application-type: servlet
  autoconfigure:
    exclude:
      - com.alicp.jetcache.autoconfigure.JetCacheAutoConfiguration
      - com.ulisesbocchio.jasyptspringbootstarter.JasyptSpringBootAutoConfiguration
#      - org.apache.rocketmq.spring.autoconfigure.RocketMQAutoConfiguration
      - org.springframework.boot.autoconfigure.amqp.RabbitAutoConfiguration
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
      - com.alibaba.druid.spring.boot.autoconfigure.DruidDataSourceAutoConfigure
#      - org.springframework.boot.autoconfigure.data.redis.RedisAutoConfiguration
      - org.springframework.boot.autoconfigure.data.elasticsearch.ElasticsearchDataAutoConfiguration
      - org.springframework.boot.autoconfigure.data.elasticsearch.ElasticsearchRepositoriesAutoConfiguration
      - org.springframework.boot.autoconfigure.mongo.MongoAutoConfiguration
      - org.springframework.boot.autoconfigure.data.mongo.MongoDataAutoConfiguration
      - com.yomahub.liteflow.springboot.config.LiteflowMainAutoConfiguration