apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: tomcat-deploy
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: tomcat-cluster
    spec:
      volumes:
        - name: webapp
          hostPath:
            path: /mnt
      containers:
        - name: tomcat-cluster
          image: tomcat:8.5.46-jdk8-openjdk
          resources:
            requests:
              cpu: 0.5
              memory: 200Mi
            limits:
              cpu: 1
              memory: 512Mi
          ports:
            - containerPort: 8080
          volumeMounts:
            - name: webapp
              mountPath: /usr/local/tomcat/webapps