spring:
  datasource:
    type:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/study
    username: postgres
    password: admin
    druid:
      maxActive: 50
      initialSize: 10
      maxWait: 60000
      minIdle: 6
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000
      validationQuery: select 'x'
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      poolPreparedStatements: true
      maxOpenPreparedStatements: 20
    dynamic:
      enable: true
      dataSources:
        - driver-class-name: org.postgresql.Driver
          url: jdbc:postgresql://localhost:5432/study
          username: postgres
          password: admin